{{- if (and (not .Values.useExternalConfig) (not .Values.useConfigMap)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cortex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  {{- if .Values.tls.enabled }}
  cortex.yaml: {{ tpl (mergeOverwrite (tpl (toYaml .Values.config) . | fromYaml) .Values.tls.config | toYaml) . | b64enc | quote }}
  {{- else }}
  cortex.yaml: {{ tpl (toYaml .Values.config) . | b64enc | quote }}
  {{- end }}
{{- end }}
